# Generated by Django 2.0.5 on 2018-09-10 10:08

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='description', unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Assign',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('lead_start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='staff', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Department Leads',
                'ordering': ['added_date'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Asset Owners',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('work_email', models.EmailField(max_length=254)),
                ('work_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('residential_address', models.CharField(default='', max_length=255)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='first_name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('assets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ams.Assets')),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('ams.assets',),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('assets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ams.Assets')),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('published_by', models.CharField(blank=True, max_length=255)),
                ('publish_date', models.DateField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('ams.assets',),
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('assets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ams.Assets')),
            ],
            options={
                'abstract': False,
            },
            bases=('ams.assets',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('assets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ams.Assets')),
                ('purchase_date', models.DateField(blank=True, default='')),
                ('expiry_date', models.DateField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('ams.assets',),
        ),
        migrations.AddField(
            model_name='staff',
            name='asset',
            field=models.ManyToManyField(related_name='staff_assets', through='ams.Assign', to='ams.Assets'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_department', to='ams.Department'),
        ),
        migrations.AddField(
            model_name='owner',
            name='assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_owner', to='ams.Assets'),
        ),
        migrations.AddField(
            model_name='owner',
            name='department_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_owner', to='ams.DepartmentLead'),
        ),
        migrations.AddField(
            model_name='departmentlead',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='team_leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead', to='ams.DepartmentLead'),
        ),
        migrations.AddField(
            model_name='assign',
            name='assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_assign', to='ams.Assets'),
        ),
        migrations.AddField(
            model_name='assign',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assign', to='ams.Staff'),
        ),
    ]
