# Generated by Django 2.0.5 on 2018-10-07 14:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('lead_start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='staff', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Department Leads',
                'ordering': ['added_date'],
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('asset_type', models.CharField(default='Hardware', editable=False, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, default='')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='description', unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='HardwareAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_assign', to='ams.Hardware')),
            ],
            options={
                'verbose_name': 'Hardware Assignment',
                'verbose_name_plural': 'Hardware Assignments',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='HardwareOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_owner', to='ams.Hardware')),
                ('department_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hardware_owner', to='ams.DepartmentLead')),
            ],
            options={
                'verbose_name': 'Hardware Owner',
                'verbose_name_plural': 'Hardware Owners',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('asset_type', models.CharField(default='Information', editable=False, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('publish_date', models.DateField(blank=True, default='')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='description', unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='InformationAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_assign', to='ams.Information')),
            ],
            options={
                'verbose_name': 'Information Assignment',
                'verbose_name_plural': 'Information Assignments',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='InformationOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_owner', to='ams.Information')),
                ('department_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_information_owner', to='ams.DepartmentLead')),
            ],
            options={
                'verbose_name': 'Information Owner',
                'verbose_name_plural': 'Information Owners',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('asset_type', models.CharField(default='Infrastructure', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='description', unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_assign', to='ams.Infrastructure')),
            ],
            options={
                'verbose_name': 'Infrastructure Assignment',
                'verbose_name_plural': 'Infrastructure Assignments',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_owner', to='ams.Infrastructure')),
                ('department_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_infrastructure_owner', to='ams.DepartmentLead')),
            ],
            options={
                'verbose_name': 'Infrastructure Owner',
                'verbose_name_plural': 'Infrastructure Owners',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('asset_type', models.CharField(default='Software', editable=False, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Licensed', 'Licensed'), ('Unlicensed', 'Unlicensed'), ('Expired', 'Expired')], max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('purchase_date', models.DateField(blank=True, default='')),
                ('expiry_date', models.DateField(blank=True, default='')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='description', unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_assign', to='ams.Software')),
            ],
            options={
                'verbose_name': 'Software Assignment',
                'verbose_name_plural': 'Software Assignments',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_owner', to='ams.Software')),
                ('department_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_software_owner', to='ams.DepartmentLead')),
            ],
            options={
                'verbose_name': 'Software Owner',
                'verbose_name_plural': 'Software Owners',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('work_email', models.EmailField(max_length=254)),
                ('work_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('residential_address', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='first_name', unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_department', to='ams.Department')),
                ('hardware_asset', models.ManyToManyField(related_name='staff_hardware', through='ams.HardwareAssign', to='ams.Hardware')),
                ('information_asset', models.ManyToManyField(related_name='staff_information', through='ams.InformationAssign', to='ams.Information')),
                ('infrastructure_asset', models.ManyToManyField(related_name='staff_infrastructure', through='ams.InfrastructureAssign', to='ams.Infrastructure')),
                ('software_asset', models.ManyToManyField(related_name='staff_software', through='ams.SoftwareAssign', to='ams.Software')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='softwareassign',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_software_assign', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='software',
            name='staff',
            field=models.ManyToManyField(related_name='assets_software_staff', through='ams.SoftwareAssign', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='infrastructureassign',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_infrastructure_assign', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='staff',
            field=models.ManyToManyField(related_name='assets_infrastructure_staff', through='ams.InfrastructureAssign', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='informationassign',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_information_assign', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='information',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_staff', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='information',
            name='staff',
            field=models.ManyToManyField(related_name='assets_information_staff', through='ams.InformationAssign', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='hardwareassign',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_hardware_assign', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='staff',
            field=models.ManyToManyField(related_name='assets_hardware_staff', through='ams.HardwareAssign', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='departmentlead',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_staff', to='ams.Staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='team_leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead', to='ams.DepartmentLead'),
        ),
    ]
