# Generated by Django 2.0.5 on 2018-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='image',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
