# Generated by Django 2.0.5 on 2018-09-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_staff', to='ams.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='residential_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
