# Generated by Django 2.0.5 on 2018-10-13 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ams', '0002_auto_20181011_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwareassign',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='hardwareassign',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='informationassign',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='informationassign',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='infrastructureassign',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='infrastructureassign',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='softwareassign',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='softwareassign',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='hardwareassign',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardwareassign',
            name='approve_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='hardwareassign',
            name='assign_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_assign_by', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='hardwareassign',
            name='return_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardwareassign',
            name='return_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='informationassign',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informationassign',
            name='approve_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='informationassign',
            name='assign_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_assign_by', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='informationassign',
            name='return_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informationassign',
            name='return_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='infrastructureassign',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infrastructureassign',
            name='approve_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='infrastructureassign',
            name='assign_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_assign_by', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='infrastructureassign',
            name='return_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infrastructureassign',
            name='return_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='softwareassign',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwareassign',
            name='approve_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='softwareassign',
            name='assign_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_assign_by', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='softwareassign',
            name='return_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwareassign',
            name='return_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
