# Generated by Django 2.0.5 on 2018-09-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_auto_20180911_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='staff',
            field=models.ManyToManyField(related_name='assets_staff', through='ams.Assign', to='ams.Staff'),
        ),
    ]
