# Generated by Django 2.0.5 on 2018-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_auto_20181107_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
