# Generated by Django 2.0.5 on 2018-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_auto_20181107_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
