# Generated by Django 2.0.5 on 2018-10-13 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_auto_20181013_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassign',
            name='approve_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
