# Generated by Django 2.0.5 on 2018-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_auto_20181108_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
