# Generated by Django 2.0.5 on 2018-11-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_auto_20181108_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='software',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
