# Generated by Django 2.0.5 on 2018-10-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_auto_20181014_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassign',
            name='assign_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_assign_by', to='users.UserProfile'),
        ),
    ]
