# Generated by Django 2.0.5 on 2018-10-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_auto_20181018_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassign',
            name='approve',
            field=models.BooleanField(),
        ),
    ]
