# Generated by Django 2.0.5 on 2018-11-11 17:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0010_auto_20181109_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='date_assigned', unique=True),
        ),
    ]
