# Generated by Django 2.0.5 on 2018-10-18 20:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_auto_20181018_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='date_assigned', unique=True),
        ),
        migrations.AddField(
            model_name='infrastructureassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='date_assigned', unique=True),
        ),
        migrations.AddField(
            model_name='softwareassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='date_assigned', unique=True),
        ),
        migrations.AlterField(
            model_name='hardwareassign',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hardwareassign',
            name='approve_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hardwareassign',
            name='return_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='informationassign',
            name='approve_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='informationassign',
            name='return_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureassign',
            name='approve_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureassign',
            name='return_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='softwareassign',
            name='approve_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='softwareassign',
            name='return_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
