# Generated by Django 2.0.5 on 2018-11-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0012_auto_20181111_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='staff',
            field=models.ManyToManyField(related_name='assets_hardware_staff', through='ams.Hardwareassign', to='ams.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hardware_asset',
            field=models.ManyToManyField(related_name='staff_hardware', through='ams.Hardwareassign', to='ams.Hardware'),
        ),
    ]
