# Generated by Django 2.0.5 on 2018-10-19 08:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0012_auto_20181018_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='staff', unique=True),
        ),
        migrations.AlterField(
            model_name='informationassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='staff', unique=True),
        ),
        migrations.AlterField(
            model_name='infrastructureassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='staff', unique=True),
        ),
        migrations.AlterField(
            model_name='softwareassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='staff', unique=True),
        ),
    ]
