# Generated by Django 2.0.5 on 2018-11-05 10:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_auto_20181019_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='assets', unique=True),
        ),
        migrations.AlterField(
            model_name='informationassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='assets', unique=True),
        ),
        migrations.AlterField(
            model_name='infrastructureassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='assets', unique=True),
        ),
        migrations.AlterField(
            model_name='softwareassign',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='assets', unique=True),
        ),
    ]
