# Generated by Django 2.0.5 on 2018-11-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_auto_20181111_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'get_latest_by': ['added_date'], 'ordering': ['-added_date']},
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'get_latest_by': ['date_added'], 'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'get_latest_by': ['date_added'], 'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'get_latest_by': ['date_added'], 'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'get_latest_by': ['date_added'], 'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'get_latest_by': ['date_added'], 'ordering': ['-date_added'], 'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='departmentlead',
            name='is_lead',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
